//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franch
    {
        public int Franch_ID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string InternalFranchName { get; set; }
        public string ContactInfo { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string SiteName { get; set; }
        public string ServerName { get; set; }
        public string DbName { get; set; }
        public string RegionCode { get; set; }
        public string AdditionalPeriod { get; set; }
        public string LogName { get; set; }
        public string ImgTel { get; set; }
        public string lnkHeadUrl { get; set; }
        public bool isLite { get; set; }
        public string BankAccount { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string CompanyName { get; set; }
        public string CorrAccount { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public int PriceSearchCommandTimeOut { get; set; }
        public int ClientGroup { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<bool> IsConsultantOn { get; set; }
        public Nullable<int> liveTexID { get; set; }
        public bool SBRFPaymentAPIEnabled { get; set; }
        public string SBRFPaymentUserName { get; set; }
        public string SBRFPaymentUserPassword { get; set; }
        public Nullable<int> AdditionalPeriodAvia { get; set; }
        public Nullable<decimal> CustomFactorAvia { get; set; }
        public bool ShowSupplyPriceClientCartRMM { get; set; }
        public bool RestrictionsOnRMM { get; set; }
        public bool IsStandAlone { get; set; }
        public string SBRFPaymentApiUrl { get; set; }
        public string PaymentApiUrl { get; set; }
        public bool PaymentAPIEnabled { get; set; }
        public string PaymentUserName { get; set; }
        public string PaymentUserPassword { get; set; }
    }
}
