//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRequests
    {
        public int ID { get; set; }
        public string RequestType { get; set; }
        public string RequestData { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ResponseData { get; set; }
    }
}
