//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLineStatusChanges
    {
        public int OrderLineStatusChangeID { get; set; }
        public int OrderLineID { get; set; }
        public byte OrderLineStatus { get; set; }
        public string StatusChangeInfo { get; set; }
        public System.DateTime StatusChangeTime { get; set; }
        public Nullable<byte> ClientReaction { get; set; }
        public Nullable<System.DateTime> ClientReactionTime { get; set; }
    
        public virtual OrderLineStatuses OrderLineStatuses { get; set; }
        public virtual OrderLines OrderLines { get; set; }
    }
}
