//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLineStatuses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderLineStatuses()
        {
            this.OrderLines = new HashSet<OrderLines>();
        }
    
        public byte OrderLineStatusID { get; set; }
        public string NameRMS { get; set; }
        public string NameHansa { get; set; }
        public bool IsFinal { get; set; }
        public bool RequiresClientReaction { get; set; }
        public bool ExcludeFromTotalSum { get; set; }
        public bool SendToAcctg { get; set; }
        public string Manager { get; set; }
        public string Client { get; set; }
        public bool ClientShow { get; set; }
        public int ClientShowOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLines> OrderLines { get; set; }
    }
}
