//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistoryDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int CountOrder { get; set; }
        public int CountPlaced { get; set; }
        public decimal PriceOrder { get; set; }
        public decimal PricePlaced { get; set; }
        public int Status { get; set; }
        public string Reference { get; set; }
    
        public virtual OrderHistory OrderHistory { get; set; }
    }
}
