//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderLines = new HashSet<OrderLines>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public string ClientID { get; set; }
        public byte ShippingMethod { get; set; }
        public byte PaymentMethod { get; set; }
        public string OrderNotes { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string StoreNumber { get; set; }
        public string CustOrderNum { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public decimal Total { get; set; }
        public bool IsTest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLines> OrderLines { get; set; }
        public virtual Users Users { get; set; }
    }
}
