//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchSparePartsLog
    {
        public System.DateTime SearchDate { get; set; }
        public string PartNumber { get; set; }
        public string ClientIP { get; set; }
        public string Manufacturer { get; set; }
        public string SourcePage { get; set; }
        public string AcctgID { get; set; }
        public long ID { get; set; }
        public Nullable<int> SearchType { get; set; }
        public Nullable<int> Source { get; set; }
    }
}
