//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpareParts
    {
        public string Manufacturer { get; set; }
        public string PartNumber { get; set; }
        public string InternalPartNumber { get; set; }
        public string PartName { get; set; }
        public string PartDescription { get; set; }
        public int SupplierID { get; set; }
        public int DeliveryDaysMin { get; set; }
        public int DeliveryDaysMax { get; set; }
        public decimal InitialPrice { get; set; }
        public string RgCode { get; set; }
        public Nullable<decimal> WeightPhysical { get; set; }
        public Nullable<decimal> WeightVolume { get; set; }
        public Nullable<int> QtyInStock { get; set; }
        public Nullable<int> MinOrderQty { get; set; }
        public Nullable<decimal> PriceConstantTerm { get; set; }
        public System.DateTime PriceDate { get; set; }
        public Nullable<int> SparePartGroupID { get; set; }
        public string Region { get; set; }
        public int SizeID { get; set; }
    }
}
