//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSAutoAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Settings = new HashSet<Settings>();
            this.Orders = new HashSet<Orders>();
            this.Permissions = new HashSet<Permissions>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public byte UserRole { get; set; }
        public string AcctgID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public bool IsChanged { get; set; }
        public string ClientName { get; set; }
        public string Email { get; set; }
        public byte TradingVolume { get; set; }
        public byte ClientCategory { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string Locality { get; set; }
        public string ContactLastName { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactMiddleName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactExtPhone { get; set; }
        public string ScopeType { get; set; }
        public string HowKnow { get; set; }
        public string RmsStoreID { get; set; }
        public string ManagerId { get; set; }
        public string ManagerDeptId { get; set; }
        public bool IsChecked { get; set; }
        public bool IsRestricted { get; set; }
        public int ClientGroup { get; set; }
        public decimal PrepaymentPercent { get; set; }
        public decimal PersonalMarkup { get; set; }
        public int ReclamationPeriod { get; set; }
        public decimal Balance { get; set; }
        public decimal DelayCredit { get; set; }
        public System.DateTime BalanceDate { get; set; }
        public string InternalFranchName { get; set; }
        public System.Guid UserGuid { get; set; }
        public string VIN1 { get; set; }
        public string VIN2 { get; set; }
        public string VIN3 { get; set; }
        public int PriceHistoryDays { get; set; }
        public Nullable<int> PassportSeries { get; set; }
        public Nullable<int> PassportNumber { get; set; }
        public string PassportIssuedBy { get; set; }
        public Nullable<System.DateTime> PassportWhenIssued { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settings> Settings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permissions> Permissions { get; set; }
    }
}
